### ISSUE TITLE
MicrosoftAppId and MicrosoftAppPassword missing from config file

### ISSUE THREAD

**Issue by msimecek** [martinkearn/Bot-Starter-Template#16]
`appsettings.json` doesn't contain properties for MicrosoftAppId and MicrosoftAppPassword which are referenced from `ConfigurationCredentialProvider`. Providing them along with the other properties will make it easier to start.

**Comment by martinkearn** [comment]
Fixed in 009cb05146b9433fa5e5add29392b59d72ce2c36
